### ISSUE TITLE
assets.get_asset_info function returns wrong "decimals" value. Different from blockfrost_api.asset function that it uses.

### ISSUE THREAD

**Issue by SpawnDev** [theeldermillenial/minswap-py#11]
```
from minswap import assets, pools
from blockfrost import BlockFrostApi, ApiError, ApiUrls

blockfrost_api = BlockFrostApi(project_id='API_KEY',base_url=ApiUrls.mainnet.value)

asset_name = "133fac9e153194428eb0919be39837b42b9e977fc7298f3ff1b76ef95055444759"

info = assets.get_asset_info(pool.unit_b)
print(info)
info2 = blockfrost_api.asset(pool.unit_b)
print(info2)
```

This function prints out two different values for "decimals". minswap returns "0" (Wrong), while blockfrost returns "6" (Correct).

Additional info:
While implementing workaround using Blockfrost, I noticed that for some assets "metadata" can be Null value, which defaults "decimals" to 0. Furthermore, even if "metadata" value is not Null, "metadata.decimals" could be Null, which also defaults "decimals" value to 0.

Not exactly relevant for this issue, as expected value is 6, but could be related to this as error while handling metadata returns 0.

**Comment by theeldermillenial** [comment]
Thanks, I'll take a look into this in the next 24 hours.

**Comment by Nicholas-Schaub** [comment]
@SpawnDev I think the issue is that the token metadata was updated. What `minswap-py` does, to help reduce blockfrost call frequency, is cache asset information and uses the cache rather than make a call to blockfrost every time.

The first time I ran your code, I got the exact same result as you. The decimals was 0 for `get_asset_info`, and was 6 for the blockfrost call.

When I did `get_asset_info(asset_name, update_cache=True)`, I then got the proper result of 6 for the decimals.

**Comment by theeldermillenial** [comment]
@SpawnDev I think the issue here is that `minswap-py` caches data on the backend to help reduce the number of blockfrost calls. I ran your code, and got the exact same result. However, when I added `update_cache=True` to the `get_asset_info` function, I got the same result as blockfrost.

See the modified version of your code below:
```python
from minswap import assets, pools
from blockfrost import BlockFrostApi, ApiError, ApiUrls

blockfrost_api = BlockFrostApi(
    project_id="API_KEY", base_url=ApiUrls.mainnet.value
)

asset_name = "133fac9e153194428eb0919be39837b42b9e977fc7298f3ff1b76ef95055444759"

info = assets.get_asset_info(asset_name, update_cache=True)
print(info)
info2 = blockfrost_api.asset(asset_name)
print(info2)

```

**Comment by SpawnDev** [comment]
Yes, that seems to work. Thanks for reply!
